// Code generated by protoc-gen-go.
// source: agentpb/agent.proto
// DO NOT EDIT!

/*
Package agentpb is a generated protocol buffer package.

It is generated from these files:
	agentpb/agent.proto

It has these top-level messages:
	StatusRequest
	StatusResponse
	LocalStatusRequest
	LocalStatusResponse
	SystemStatus
	Node
	NodeStatus
	Probe
	Timestamp
*/
package agentpb

import proto "github.com/gravitational/planet/Godeps/_workspace/src/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "github.com/gravitational/planet/Godeps/_workspace/src/golang.org/x/net/context"
	grpc "github.com/gravitational/planet/Godeps/_workspace/src/google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MemberStatusType int32

const (
	MemberStatusType_MemberNone    MemberStatusType = 0
	MemberStatusType_MemberAlive   MemberStatusType = 1
	MemberStatusType_MemberLeaving MemberStatusType = 2
	MemberStatusType_MemberLeft    MemberStatusType = 3
	MemberStatusType_MemberFailed  MemberStatusType = 4
)

var MemberStatusType_name = map[int32]string{
	0: "MemberNone",
	1: "MemberAlive",
	2: "MemberLeaving",
	3: "MemberLeft",
	4: "MemberFailed",
}
var MemberStatusType_value = map[string]int32{
	"MemberNone":    0,
	"MemberAlive":   1,
	"MemberLeaving": 2,
	"MemberLeft":    3,
	"MemberFailed":  4,
}

func (x MemberStatusType) String() string {
	return proto.EnumName(MemberStatusType_name, int32(x))
}
func (MemberStatusType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusType int32

const (
	StatusType_SystemUnknown  StatusType = 0
	StatusType_SystemRunning  StatusType = 1
	StatusType_SystemDegraded StatusType = 2
)

var StatusType_name = map[int32]string{
	0: "SystemUnknown",
	1: "SystemRunning",
	2: "SystemDegraded",
}
var StatusType_value = map[string]int32{
	"SystemUnknown":  0,
	"SystemRunning":  1,
	"SystemDegraded": 2,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}
func (StatusType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ServiceStatusType int32

const (
	ServiceStatusType_ServiceUnknown    ServiceStatusType = 0
	ServiceStatusType_ServiceRunning    ServiceStatusType = 1
	ServiceStatusType_ServiceFailed     ServiceStatusType = 2
	ServiceStatusType_ServiceTerminated ServiceStatusType = 3
)

var ServiceStatusType_name = map[int32]string{
	0: "ServiceUnknown",
	1: "ServiceRunning",
	2: "ServiceFailed",
	3: "ServiceTerminated",
}
var ServiceStatusType_value = map[string]int32{
	"ServiceUnknown":    0,
	"ServiceRunning":    1,
	"ServiceFailed":     2,
	"ServiceTerminated": 3,
}

func (x ServiceStatusType) String() string {
	return proto.EnumName(ServiceStatusType_name, int32(x))
}
func (ServiceStatusType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusResponse struct {
	Status *SystemStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	// Human-readable status summary.
	Summary string `protobuf:"bytes,2,opt,name=summary" json:"summary,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusResponse) GetStatus() *SystemStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type LocalStatusRequest struct {
}

func (m *LocalStatusRequest) Reset()                    { *m = LocalStatusRequest{} }
func (m *LocalStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusRequest) ProtoMessage()               {}
func (*LocalStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LocalStatusResponse struct {
	Status *NodeStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *LocalStatusResponse) Reset()                    { *m = LocalStatusResponse{} }
func (m *LocalStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusResponse) ProtoMessage()               {}
func (*LocalStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LocalStatusResponse) GetStatus() *NodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// SystemStatus describes the health status of the cluster.
type SystemStatus struct {
	Status StatusType `protobuf:"varint,1,opt,name=status,enum=agentpb.StatusType" json:"status,omitempty"`
	// Current list of members of the serf cluster.
	Nodes []*Node `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	// Health status of individual nodes.
	NodeStatuses []*NodeStatus `protobuf:"bytes,3,rep,name=node_statuses" json:"node_statuses,omitempty"`
}

func (m *SystemStatus) Reset()                    { *m = SystemStatus{} }
func (m *SystemStatus) String() string            { return proto.CompactTextString(m) }
func (*SystemStatus) ProtoMessage()               {}
func (*SystemStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SystemStatus) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *SystemStatus) GetNodeStatuses() []*NodeStatus {
	if m != nil {
		return m.NodeStatuses
	}
	return nil
}

type Node struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Addr   string            `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Status MemberStatusType  `protobuf:"varint,3,opt,name=status,enum=agentpb.MemberStatusType" json:"status,omitempty"`
	Tags   map[string]string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Node) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// NodeStatus represents a result of a health check for a single node.
type NodeStatus struct {
	Name   string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Status StatusType `protobuf:"varint,2,opt,name=status,enum=agentpb.StatusType" json:"status,omitempty"`
	// Probes lists all the health probes collected during the health check.
	// For simplicity, only probes for alerts are collected.  Thus, for a healthy
	// system, the Probes will be empty.
	Probes []*Probe `protobuf:"bytes,3,rep,name=probes" json:"probes,omitempty"`
}

func (m *NodeStatus) Reset()                    { *m = NodeStatus{} }
func (m *NodeStatus) String() string            { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()               {}
func (*NodeStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeStatus) GetProbes() []*Probe {
	if m != nil {
		return m.Probes
	}
	return nil
}

type Probe struct {
	Timestamp *Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Name of the checker that generated the probe.
	Checker string `protobuf:"bytes,2,opt,name=checker" json:"checker,omitempty"`
	// Auxiliary field that can be used to provide additional details of the
	// checker activity.
	Extra  string            `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
	Status ServiceStatusType `protobuf:"varint,4,opt,name=status,enum=agentpb.ServiceStatusType" json:"status,omitempty"`
	Error  string            `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *Probe) Reset()                    { *m = Probe{} }
func (m *Probe) String() string            { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()               {}
func (*Probe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Probe) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Timestamp struct {
	Seconds     int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanoseconds int32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*StatusRequest)(nil), "agentpb.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "agentpb.StatusResponse")
	proto.RegisterType((*LocalStatusRequest)(nil), "agentpb.LocalStatusRequest")
	proto.RegisterType((*LocalStatusResponse)(nil), "agentpb.LocalStatusResponse")
	proto.RegisterType((*SystemStatus)(nil), "agentpb.SystemStatus")
	proto.RegisterType((*Node)(nil), "agentpb.Node")
	proto.RegisterType((*NodeStatus)(nil), "agentpb.NodeStatus")
	proto.RegisterType((*Probe)(nil), "agentpb.Probe")
	proto.RegisterType((*Timestamp)(nil), "agentpb.Timestamp")
	proto.RegisterEnum("agentpb.MemberStatusType", MemberStatusType_name, MemberStatusType_value)
	proto.RegisterEnum("agentpb.StatusType", StatusType_name, StatusType_value)
	proto.RegisterEnum("agentpb.ServiceStatusType", ServiceStatusType_name, ServiceStatusType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Agent service

type AgentClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	LocalStatus(ctx context.Context, in *LocalStatusRequest, opts ...grpc.CallOption) (*LocalStatusResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/agentpb.Agent/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) LocalStatus(ctx context.Context, in *LocalStatusRequest, opts ...grpc.CallOption) (*LocalStatusResponse, error) {
	out := new(LocalStatusResponse)
	err := grpc.Invoke(ctx, "/agentpb.Agent/LocalStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	LocalStatus(context.Context, *LocalStatusRequest) (*LocalStatusResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AgentServer).Status(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Agent_LocalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LocalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AgentServer).LocalStatus(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agentpb.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Agent_Status_Handler,
		},
		{
			MethodName: "LocalStatus",
			Handler:    _Agent_LocalStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xe3, 0x24, 0x55, 0x26, 0x4d, 0xea, 0x6e, 0xdb, 0xaf, 0xf9, 0x02, 0x17, 0x95, 0x91,
	0x10, 0x6a, 0x45, 0x80, 0x72, 0x41, 0x05, 0x57, 0x45, 0x50, 0x24, 0x54, 0x2a, 0xe4, 0x86, 0x0b,
	0xae, 0xd0, 0x26, 0x19, 0xd2, 0xa8, 0xf1, 0x3a, 0xac, 0xd7, 0x81, 0xbc, 0x05, 0xd7, 0xbc, 0x06,
	0x0f, 0xc1, 0x6b, 0xb1, 0x7f, 0x5e, 0x3b, 0x3f, 0x12, 0x57, 0xd9, 0x39, 0x73, 0x76, 0xce, 0x99,
	0xf1, 0x64, 0x61, 0x9f, 0x8e, 0x91, 0x89, 0xd9, 0xe0, 0x89, 0xfe, 0xed, 0xcd, 0x78, 0x22, 0x12,
	0xb2, 0x6d, 0xc1, 0x70, 0x17, 0x5a, 0x37, 0x82, 0x8a, 0x2c, 0x8d, 0xf0, 0x5b, 0x86, 0xa9, 0x08,
	0x3f, 0x43, 0x3b, 0x07, 0xd2, 0x59, 0xc2, 0x52, 0x24, 0x8f, 0xa1, 0x9e, 0x6a, 0xa4, 0xe3, 0x1d,
	0x7b, 0x8f, 0x9a, 0x67, 0x87, 0x3d, 0x7b, 0xb9, 0x77, 0xb3, 0x48, 0x05, 0xc6, 0x96, 0x6e, 0x49,
	0xa4, 0x03, 0xdb, 0x69, 0x16, 0xc7, 0x94, 0x2f, 0x3a, 0x15, 0xc9, 0x6f, 0x44, 0x79, 0x18, 0x1e,
	0x00, 0xb9, 0x4a, 0x86, 0x74, 0xba, 0x2c, 0xf8, 0x1a, 0xf6, 0x97, 0x50, 0xab, 0x7a, 0xba, 0xa2,
	0xba, 0xef, 0x54, 0xaf, 0x93, 0x11, 0x2e, 0x6b, 0x86, 0xbf, 0x3c, 0xd8, 0x29, 0x9b, 0x59, 0xb9,
	0xdd, 0x2e, 0xdd, 0x36, 0x84, 0xfe, 0x62, 0x86, 0xce, 0xf1, 0x03, 0xa8, 0x31, 0x59, 0x33, 0x95,
	0x7e, 0x7d, 0xa9, 0xd4, 0x5a, 0x52, 0x8a, 0x4c, 0x8e, 0x9c, 0x43, 0x4b, 0x1d, 0xbe, 0x98, 0x3b,
	0x92, 0xec, 0x6b, 0xf2, 0x46, 0x5b, 0x3b, 0xcc, 0x9d, 0x31, 0x0d, 0xff, 0x78, 0x50, 0x55, 0x49,
	0x42, 0xa0, 0xca, 0x68, 0x8c, 0xda, 0x52, 0x23, 0xd2, 0x67, 0x85, 0xd1, 0xd1, 0x88, 0xdb, 0x51,
	0xe9, 0x33, 0x79, 0xe6, 0xcc, 0xfb, 0xda, 0xfc, 0xff, 0x4e, 0xe3, 0x03, 0xc6, 0x03, 0xe4, 0x1b,
	0x5a, 0x38, 0x85, 0xaa, 0xa0, 0xe3, 0xb4, 0x53, 0xd5, 0xa6, 0x8e, 0x96, 0x4c, 0xf5, 0xfa, 0x32,
	0xf3, 0x96, 0x09, 0xbe, 0x88, 0x34, 0xa9, 0xfb, 0x02, 0x1a, 0x0e, 0x22, 0x01, 0xf8, 0x77, 0xb8,
	0xb0, 0x9e, 0xd4, 0x91, 0x1c, 0x40, 0x6d, 0x4e, 0xa7, 0x19, 0x5a, 0x4f, 0x26, 0x78, 0x59, 0x39,
	0xf7, 0xc2, 0x0c, 0xa0, 0xe8, 0x72, 0x63, 0x3b, 0xc5, 0xdc, 0x2b, 0xff, 0x9e, 0xfb, 0x43, 0xa8,
	0xcb, 0x6d, 0x1c, 0xb8, 0x59, 0xb6, 0x1d, 0xf9, 0xa3, 0x82, 0x23, 0x9b, 0x0d, 0x7f, 0x7b, 0x50,
	0xd3, 0x08, 0x79, 0x0a, 0x0d, 0x31, 0x89, 0xe5, 0xd6, 0xd0, 0x78, 0x66, 0xf7, 0x82, 0xb8, 0x4b,
	0xfd, 0x3c, 0x13, 0x15, 0x24, 0xb5, 0x8d, 0xc3, 0x5b, 0x1c, 0xde, 0x61, 0x3e, 0xe2, 0x3c, 0x54,
	0x6d, 0xe2, 0x0f, 0xc1, 0xa9, 0x1e, 0xb2, 0x6c, 0x53, 0x07, 0xe4, 0xcc, 0x35, 0x50, 0xd5, 0x0d,
	0x74, 0x8b, 0x06, 0x90, 0xcf, 0x27, 0x43, 0xdc, 0xd0, 0x87, 0xaa, 0xc4, 0x79, 0xc2, 0x3b, 0x35,
	0x5b, 0x49, 0x05, 0xe1, 0x3b, 0x39, 0xe5, 0xb2, 0x8d, 0x14, 0x87, 0x09, 0x1b, 0x99, 0x85, 0xf4,
	0xa3, 0x3c, 0x24, 0xc7, 0xd0, 0x64, 0x94, 0x25, 0x79, 0x56, 0x99, 0xac, 0x45, 0x65, 0xe8, 0xe4,
	0x16, 0x82, 0xd5, 0xef, 0x4e, 0xda, 0x00, 0x06, 0xbb, 0x4e, 0x18, 0x06, 0x5b, 0x64, 0x17, 0x9a,
	0x26, 0xbe, 0x98, 0x4e, 0xe6, 0x18, 0x78, 0x64, 0x0f, 0x5a, 0x06, 0xb8, 0x42, 0x3a, 0x9f, 0xb0,
	0x71, 0x50, 0x29, 0xee, 0x5c, 0xe1, 0x57, 0x11, 0xf8, 0xf2, 0xcb, 0xef, 0x98, 0xf8, 0x92, 0x4e,
	0xa6, 0x38, 0x0a, 0xaa, 0x27, 0x97, 0x00, 0x25, 0x0d, 0x59, 0xc2, 0xfc, 0xa7, 0x3e, 0xb1, 0x3b,
	0x96, 0x7c, 0x67, 0x52, 0xc6, 0x41, 0x51, 0xc6, 0x98, 0xaa, 0xea, 0xc9, 0x2d, 0x68, 0x1b, 0xe8,
	0x0d, 0x8e, 0x39, 0x1d, 0xc9, 0x3a, 0x95, 0x13, 0x84, 0xbd, 0xb5, 0x69, 0x69, 0xa2, 0x01, 0x8b,
	0x7a, 0x05, 0x56, 0x14, 0x54, 0x1a, 0x06, 0xb3, 0xbe, 0x2a, 0xe4, 0xd0, 0xd5, 0xeb, 0x23, 0x8f,
	0x27, 0x8c, 0x0a, 0x09, 0xfb, 0x67, 0x3f, 0xe5, 0x5e, 0x5c, 0xa8, 0xaf, 0x43, 0x5e, 0x41, 0xdd,
	0x2e, 0xe5, 0x7f, 0x2b, 0x0b, 0x67, 0x5f, 0x99, 0xee, 0xd1, 0x1a, 0x6e, 0xde, 0x99, 0x70, 0x8b,
	0xbc, 0x87, 0x66, 0xe9, 0x01, 0x22, 0xf7, 0x1c, 0x73, 0xfd, 0xb1, 0xea, 0xde, 0xdf, 0x9c, 0xcc,
	0x6b, 0x0d, 0xea, 0xfa, 0x79, 0x7d, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xd9, 0x4b, 0xcf,
	0x75, 0x05, 0x00, 0x00,
}
