// Code generated by protoc-gen-go.
// source: agentpb/agent.proto
// DO NOT EDIT!

/*
Package agentpb is a generated protocol buffer package.

It is generated from these files:
	agentpb/agent.proto

It has these top-level messages:
	StatusRequest
	StatusResponse
	LocalStatusRequest
	LocalStatusResponse
	SystemStatus
	MemberStatus
	NodeStatus
	Probe
	Timestamp
*/
package agentpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SystemStatus_Type int32

const (
	SystemStatus_Unknown  SystemStatus_Type = 0
	SystemStatus_Running  SystemStatus_Type = 1
	SystemStatus_Degraded SystemStatus_Type = 2
)

var SystemStatus_Type_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Degraded",
}
var SystemStatus_Type_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Degraded": 2,
}

func (x SystemStatus_Type) String() string {
	return proto.EnumName(SystemStatus_Type_name, int32(x))
}
func (SystemStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type MemberStatus_Type int32

const (
	MemberStatus_None    MemberStatus_Type = 0
	MemberStatus_Alive   MemberStatus_Type = 1
	MemberStatus_Leaving MemberStatus_Type = 2
	MemberStatus_Left    MemberStatus_Type = 3
	MemberStatus_Failed  MemberStatus_Type = 4
)

var MemberStatus_Type_name = map[int32]string{
	0: "None",
	1: "Alive",
	2: "Leaving",
	3: "Left",
	4: "Failed",
}
var MemberStatus_Type_value = map[string]int32{
	"None":    0,
	"Alive":   1,
	"Leaving": 2,
	"Left":    3,
	"Failed":  4,
}

func (x MemberStatus_Type) String() string {
	return proto.EnumName(MemberStatus_Type_name, int32(x))
}
func (MemberStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type NodeStatus_Type int32

const (
	NodeStatus_Unknown  NodeStatus_Type = 0
	NodeStatus_Running  NodeStatus_Type = 1
	NodeStatus_Degraded NodeStatus_Type = 2
)

var NodeStatus_Type_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Degraded",
}
var NodeStatus_Type_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Degraded": 2,
}

func (x NodeStatus_Type) String() string {
	return proto.EnumName(NodeStatus_Type_name, int32(x))
}
func (NodeStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type Probe_Type int32

const (
	Probe_Unknown    Probe_Type = 0
	Probe_Running    Probe_Type = 1
	Probe_Failed     Probe_Type = 2
	Probe_Terminated Probe_Type = 3
)

var Probe_Type_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Failed",
	3: "Terminated",
}
var Probe_Type_value = map[string]int32{
	"Unknown":    0,
	"Running":    1,
	"Failed":     2,
	"Terminated": 3,
}

func (x Probe_Type) String() string {
	return proto.EnumName(Probe_Type_name, int32(x))
}
func (Probe_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusResponse struct {
	Status *SystemStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	// Human-readable status summary.
	Summary string `protobuf:"bytes,2,opt,name=summary" json:"summary,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusResponse) GetStatus() *SystemStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type LocalStatusRequest struct {
}

func (m *LocalStatusRequest) Reset()                    { *m = LocalStatusRequest{} }
func (m *LocalStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusRequest) ProtoMessage()               {}
func (*LocalStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LocalStatusResponse struct {
	Status *NodeStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *LocalStatusResponse) Reset()                    { *m = LocalStatusResponse{} }
func (m *LocalStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusResponse) ProtoMessage()               {}
func (*LocalStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LocalStatusResponse) GetStatus() *NodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// System describes the health status of the cluster.
type SystemStatus struct {
	Status SystemStatus_Type `protobuf:"varint,1,opt,name=status,enum=agentpb.SystemStatus_Type" json:"status,omitempty"`
	// Health status of individual nodes.
	Nodes []*NodeStatus `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *SystemStatus) Reset()                    { *m = SystemStatus{} }
func (m *SystemStatus) String() string            { return proto.CompactTextString(m) }
func (*SystemStatus) ProtoMessage()               {}
func (*SystemStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SystemStatus) GetNodes() []*NodeStatus {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// MembereStatus represents the status of a member of the serf cluster.
type MemberStatus struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Addr   string            `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Status MemberStatus_Type `protobuf:"varint,3,opt,name=status,enum=agentpb.MemberStatus_Type" json:"status,omitempty"`
	Tags   map[string]string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MemberStatus) Reset()                    { *m = MemberStatus{} }
func (m *MemberStatus) String() string            { return proto.CompactTextString(m) }
func (*MemberStatus) ProtoMessage()               {}
func (*MemberStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MemberStatus) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// NodeStatus represents a result of a health check for a single node.
type NodeStatus struct {
	Name         string          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	MemberStatus *MemberStatus   `protobuf:"bytes,2,opt,name=member_status" json:"member_status,omitempty"`
	Status       NodeStatus_Type `protobuf:"varint,3,opt,name=status,enum=agentpb.NodeStatus_Type" json:"status,omitempty"`
	// Probes lists all the health probes collected during the health check.
	Probes []*Probe `protobuf:"bytes,4,rep,name=probes" json:"probes,omitempty"`
}

func (m *NodeStatus) Reset()                    { *m = NodeStatus{} }
func (m *NodeStatus) String() string            { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()               {}
func (*NodeStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeStatus) GetMemberStatus() *MemberStatus {
	if m != nil {
		return m.MemberStatus
	}
	return nil
}

func (m *NodeStatus) GetProbes() []*Probe {
	if m != nil {
		return m.Probes
	}
	return nil
}

type Probe struct {
	Timestamp *Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Name of the checker that generated the probe.
	Checker string `protobuf:"bytes,2,opt,name=checker" json:"checker,omitempty"`
	// Auxiliary field that can be used to provide additional details of the
	// checker activity.
	Extra  string     `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
	Status Probe_Type `protobuf:"varint,4,opt,name=status,enum=agentpb.Probe_Type" json:"status,omitempty"`
	Error  string     `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *Probe) Reset()                    { *m = Probe{} }
func (m *Probe) String() string            { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()               {}
func (*Probe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Probe) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Timestamp struct {
	Seconds     int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanoseconds int32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*StatusRequest)(nil), "agentpb.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "agentpb.StatusResponse")
	proto.RegisterType((*LocalStatusRequest)(nil), "agentpb.LocalStatusRequest")
	proto.RegisterType((*LocalStatusResponse)(nil), "agentpb.LocalStatusResponse")
	proto.RegisterType((*SystemStatus)(nil), "agentpb.SystemStatus")
	proto.RegisterType((*MemberStatus)(nil), "agentpb.MemberStatus")
	proto.RegisterType((*NodeStatus)(nil), "agentpb.NodeStatus")
	proto.RegisterType((*Probe)(nil), "agentpb.Probe")
	proto.RegisterType((*Timestamp)(nil), "agentpb.Timestamp")
	proto.RegisterEnum("agentpb.SystemStatus_Type", SystemStatus_Type_name, SystemStatus_Type_value)
	proto.RegisterEnum("agentpb.MemberStatus_Type", MemberStatus_Type_name, MemberStatus_Type_value)
	proto.RegisterEnum("agentpb.NodeStatus_Type", NodeStatus_Type_name, NodeStatus_Type_value)
	proto.RegisterEnum("agentpb.Probe_Type", Probe_Type_name, Probe_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Agent service

type AgentClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	LocalStatus(ctx context.Context, in *LocalStatusRequest, opts ...grpc.CallOption) (*LocalStatusResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/agentpb.Agent/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) LocalStatus(ctx context.Context, in *LocalStatusRequest, opts ...grpc.CallOption) (*LocalStatusResponse, error) {
	out := new(LocalStatusResponse)
	err := grpc.Invoke(ctx, "/agentpb.Agent/LocalStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	LocalStatus(context.Context, *LocalStatusRequest) (*LocalStatusResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AgentServer).Status(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Agent_LocalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LocalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AgentServer).LocalStatus(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agentpb.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Agent_Status_Handler,
		},
		{
			MethodName: "LocalStatus",
			Handler:    _Agent_LocalStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x8f, 0x12, 0x4d,
	0x10, 0xde, 0xf9, 0x82, 0xa5, 0x60, 0x79, 0x49, 0xb3, 0xaf, 0x4e, 0xd0, 0x44, 0x32, 0x07, 0xa3,
	0x31, 0xa2, 0x61, 0x0f, 0x9a, 0xd5, 0x98, 0xac, 0xf1, 0x23, 0x31, 0xb8, 0x31, 0xb3, 0x78, 0xf0,
	0x64, 0x1a, 0xa6, 0x44, 0x02, 0xd3, 0x83, 0x3d, 0x0d, 0xca, 0xbf, 0xf0, 0xe8, 0xc5, 0xbf, 0xe7,
	0xc1, 0x5f, 0x61, 0x77, 0xd3, 0x33, 0xcc, 0xb0, 0x6c, 0x8c, 0xa7, 0x99, 0xaa, 0xae, 0xae, 0x7a,
	0x9e, 0xa7, 0xab, 0x0a, 0xda, 0x74, 0x82, 0x4c, 0x2c, 0x46, 0x0f, 0xf4, 0xb7, 0xb7, 0xe0, 0x89,
	0x48, 0x48, 0xd5, 0x38, 0x83, 0xff, 0xe0, 0xe8, 0x42, 0x50, 0xb1, 0x4c, 0x43, 0xfc, 0xb2, 0xc4,
	0x54, 0x04, 0x1f, 0xa0, 0x99, 0x39, 0xd2, 0x45, 0xc2, 0x52, 0x24, 0xf7, 0xa1, 0x92, 0x6a, 0x8f,
	0x6f, 0x75, 0xad, 0x3b, 0xf5, 0xfe, 0xff, 0x3d, 0x73, 0xb9, 0x77, 0xb1, 0x4e, 0x05, 0xc6, 0x26,
	0xdc, 0x04, 0x11, 0x1f, 0xaa, 0xe9, 0x32, 0x8e, 0x29, 0x5f, 0xfb, 0xb6, 0x8c, 0xaf, 0x85, 0x99,
	0x19, 0x1c, 0x03, 0x19, 0x24, 0x63, 0x3a, 0x2f, 0x17, 0x7c, 0x0e, 0xed, 0x92, 0xd7, 0x54, 0xbd,
	0xb7, 0x53, 0xb5, 0x9d, 0x57, 0x3d, 0x4f, 0x22, 0x2c, 0xd7, 0x0c, 0x7e, 0x5a, 0xd0, 0x28, 0x82,
	0x21, 0xfd, 0xd2, 0xed, 0x66, 0xbf, 0xb3, 0x17, 0x73, 0x6f, 0xb8, 0x5e, 0x60, 0x0e, 0xfc, 0x2e,
	0x78, 0x4c, 0xa6, 0x4e, 0x7d, 0xa7, 0xeb, 0x5c, 0x55, 0x70, 0x13, 0x11, 0xf4, 0xc0, 0x55, 0x57,
	0x49, 0x1d, 0xaa, 0xef, 0xd9, 0x8c, 0x25, 0x5f, 0x59, 0xeb, 0x40, 0x19, 0xe1, 0x92, 0xb1, 0x29,
	0x9b, 0xb4, 0x2c, 0xd2, 0x80, 0xc3, 0x17, 0x38, 0xe1, 0x34, 0xc2, 0xa8, 0x65, 0x07, 0x3f, 0x6c,
	0x68, 0xbc, 0xc5, 0x78, 0x84, 0xdc, 0xe0, 0x23, 0xe0, 0x32, 0x1a, 0xa3, 0x46, 0x57, 0x0b, 0xf5,
	0xbf, 0xf2, 0xd1, 0x28, 0xe2, 0x46, 0x35, 0xfd, 0x5f, 0xe0, 0xe1, 0xec, 0xf0, 0x28, 0xa6, 0x2b,
	0xf3, 0x38, 0x01, 0x57, 0xd0, 0x49, 0xea, 0xbb, 0x9a, 0xc6, 0xad, 0x2b, 0x6e, 0xc8, 0x88, 0x97,
	0x4c, 0xf0, 0x75, 0xa8, 0x83, 0x3b, 0x8f, 0xa0, 0x96, 0xbb, 0x48, 0x0b, 0x9c, 0x19, 0xae, 0x0d,
	0x38, 0xf5, 0x4b, 0x8e, 0xc1, 0x5b, 0xd1, 0xf9, 0x12, 0x0d, 0xb8, 0x8d, 0x71, 0x6a, 0x3f, 0xb6,
	0x82, 0x67, 0x46, 0x8a, 0x43, 0x70, 0xcf, 0x13, 0x86, 0x52, 0x87, 0x1a, 0x78, 0x67, 0xf3, 0xe9,
	0x0a, 0xa5, 0x0a, 0x52, 0x92, 0x01, 0xd2, 0x95, 0x92, 0xc4, 0x56, 0x11, 0x03, 0xfc, 0x24, 0x5a,
	0x0e, 0x01, 0xa8, 0xbc, 0xa2, 0xd3, 0xb9, 0x94, 0xc6, 0x0d, 0x7e, 0x59, 0x00, 0x5b, 0x81, 0xf7,
	0x0a, 0x73, 0x0a, 0x47, 0xb1, 0xc6, 0xfe, 0xd1, 0x68, 0x61, 0xef, 0xf4, 0x61, 0x91, 0x59, 0xd8,
	0x88, 0x8b, 0x42, 0x3f, 0xdc, 0x11, 0xd0, 0xdf, 0xf3, 0xaa, 0x65, 0xf9, 0x6e, 0x43, 0x45, 0xce,
	0xc8, 0x08, 0x33, 0x01, 0x9b, 0xf9, 0x8d, 0x77, 0xca, 0x1d, 0x9a, 0xd3, 0x7f, 0xee, 0x81, 0xdf,
	0x16, 0x78, 0x3a, 0x83, 0xc4, 0x54, 0x13, 0xd3, 0x58, 0xf6, 0x3e, 0x8d, 0x17, 0xa6, 0xbb, 0x49,
	0x5e, 0x64, 0x98, 0x9d, 0x84, 0xdb, 0x20, 0x35, 0x53, 0xe3, 0xcf, 0x38, 0x9e, 0x61, 0xd6, 0x1d,
	0x99, 0xa9, 0x1e, 0x06, 0xbf, 0x09, 0x4e, 0x35, 0x3d, 0xf9, 0x30, 0xda, 0x28, 0x0c, 0x8f, 0xab,
	0x59, 0xb7, 0xcb, 0x1c, 0xca, 0x84, 0x55, 0x0a, 0xce, 0x13, 0xee, 0x7b, 0x26, 0x85, 0x32, 0x82,
	0xa7, 0x7f, 0xa5, 0xb7, 0x7d, 0x45, 0x9b, 0x34, 0x01, 0x86, 0xc8, 0xe3, 0x29, 0xa3, 0x42, 0xda,
	0x4e, 0xf0, 0x5a, 0xb6, 0x53, 0x11, 0x7d, 0x8a, 0xe3, 0x84, 0x45, 0x9b, 0x69, 0x74, 0xc2, 0xcc,
	0x24, 0x5d, 0xa8, 0x33, 0xca, 0x92, 0xec, 0x54, 0x71, 0xf3, 0xc2, 0xa2, 0xab, 0xff, 0x5d, 0xaa,
	0x76, 0xa6, 0xb0, 0x93, 0x27, 0x50, 0x31, 0x6f, 0x7a, 0x6d, 0x3b, 0xcc, 0xc5, 0x4d, 0xd2, 0xb9,
	0x7e, 0xc9, 0xbf, 0xd9, 0x25, 0xc1, 0x01, 0x79, 0x03, 0xf5, 0xc2, 0x92, 0x21, 0x37, 0xf2, 0xc8,
	0xcb, 0x0b, 0xa9, 0x73, 0x73, 0xff, 0x61, 0x96, 0x6b, 0x54, 0xd1, 0x2b, 0xf4, 0xe4, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xff, 0xce, 0x4d, 0x85, 0x59, 0x05, 0x00, 0x00,
}
