#!/bin/bash
#
# This is a helper script, to make it easier to access the etcd3 datastore
#

ETCDCTL_API=3 HTTP_PROXY="" HTTPS_PROXY="" http_proxy="" https_proxy="" \
/usr/bin/etcdctl-cmd --key /var/state/etcd.key --cert /var/state/etcd.cert --cacert /var/state/root.cert "$@"
