#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

: ${TARGET=releaser}
: ${OUTPUT=./build/planet}
: ${OUTPUT_FORMAT="type=local,dest=$OUTPUT"}

if [ -n "$BUILDKIT_HOST" ] && buildctl --version >/dev/null 2>&1; then
  targetFlags=""
  if [ -n "$TARGET" ]; then
    targetFlags="--opt target=$TARGET"
  fi
  buildctlCmd build \
      $targetFlags \
      --frontend=dockerfile.v0 \
      --local context=. \
      --local dockerfile=. \
      --output="$OUTPUT_FORMAT"
else
  targetFlags=""
  if [ -n "$TARGET" ]; then
    targetFlags="--target $TARGET"
  fi
  buildxCmd build \
    $targetFlags \
    --output="$OUTPUT_FORMAT" \
    .
fi
