#!/bin/bash

# enumerates Docker images given via command line arguments and deletes them if they're present
for image in $@ ; do 
	if [[ $(docker images | grep $image) ]]; then 
    	docker rmi -f $image
	else
	    echo Image $image is already gone
	fi
done
